In [ ]:
import numpy as np
import pandas as pd
import sklearn

one_year = pd.read_csv("/content/AI 2021 Data - Sheet1.csv")

one_year['Budget Per Capita'] = one_year['Budget Per Capita'].replace({'\$':''}, regex=True)

one_year['Total Population'] = one_year['Total Population'].str.replace(',','')
one_year['Murder and Nonnegligent Manslaughter'] = one_year['Murder and Nonnegligent Manslaughter'].str.replace(',','')
one_year['Violent Crimes'] = one_year['Violent Crimes'].str.replace(',','')
one_year['Total Arrests'] = one_year['Total Arrests'].str.replace(',','')
one_year['Total Population'] = one_year['Total Population'].str.replace(',','')

oneyear = pd.DataFrame(one_year)

multiple_years = pd.read_csv("/content/deaths_arrests_race - Sheet1 (1).csv")

multipleyears = pd.DataFrame(multiple_years)

In [ ]:
final_multiple_years = multiple_years.groupby(["State"]).mean().reset_index()

final_2022 = one_year.groupby(["State"]).mean().reset_index()
df = final_2022.merge(final_multiple_years, left_on=["State"], right_on=["State"], how="outer")

In [ ]:
df['Black People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Black People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Hispanic People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Hispanic People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Native American People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Native American People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Asian People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Asian People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Pacific Islanders Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Pacific Islanders Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['White People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['White People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Unknown Race People Killed by Police (1/1/2013-12/31/2019)'].fillna(value=df['Unknown Race People Killed by Police (1/1/2013-12/31/2019)'].mean(), inplace=True)
df['Black-White Dissimilarity Index (2010)'].fillna(value=df['Black-White Dissimilarity Index (2010)'].mean(), inplace=True)
df['Murder and\n  nonnegligent manslaughter'].fillna(value=df['Murder and\n  nonnegligent manslaughter'].mean(), inplace=True)
df['Violent crimes 2013 (if reported by agency)'].fillna(value=df['Violent crimes 2013 (if reported by agency)'].mean(), inplace=True)
df['Violent crimes 2014 (if reported by agency)'].fillna(value=df['Violent crimes 2014 (if reported by agency)'].mean(), inplace=True)
df['Violent crimes 2015 (if reported by agency)'].fillna(value=df['Violent crimes 2015 (if reported by agency)'].mean(), inplace=True)
df['Violent crimes 2016 (if reported by agency)'].fillna(value=df['Violent crimes 2016 (if reported by agency)'].mean(), inplace=True)
df['Violent crimes 2017 (if reported by agency)'].fillna(value=df['Violent crimes 2017 (if reported by agency)'].mean(), inplace=True)
df['Violent crimes 2018 (if reported by agency)'].fillna(value=df['Violent crimes 2018 (if reported by agency)'].mean(), inplace=True)
df['2013 Total Arrests (UCR Data)'].fillna(value=df['2013 Total Arrests (UCR Data)'].mean(), inplace=True)
df['2014 Total Arrests'].fillna(value=df['2014 Total Arrests'].mean(), inplace=True)
df['2015 Total Arrests'].fillna(value=df['2015 Total Arrests'].mean(), inplace=True)
df['2016 Total Arrests'].fillna(value=df['2016 Total Arrests'].mean(), inplace=True)
df['2017 Total Arrests'].fillna(value=df['2017 Total Arrests'].mean(), inplace=True)
df['2018 Total Arrests'].fillna(value=df['2018 Total Arrests'].mean(), inplace=True)

df['Total # of Black People Killed (2013-2021)'] = df['Black People Killed by Police'] + df['Black People Killed by Police (1/1/2013-12/31/2019)']
df['Total # of Hispanic People Killed (2013-2021)'] = df['Hispanic People Killed by Police (1/1/2013-12/31/2019)'] + df['Hispanic People Killed by Police']
df['Total # of Native American People Killed (2013-2021)'] = df['Native American People Killed by Police (1/1/2013-12/31/2019)'] + df['Native American People Killed by Police']
df['Total # of Asian People Killed (2013-2021)'] = df['Asian People Killed By Police'] + df['Asian People Killed by Police (1/1/2013-12/31/2019)']
df['Total # of Pacific Islanders Killed (2013-2021)'] = df['Pacific Islanders Killed by Police (1/1/2013-12/31/2019)'] + df['Pacific Islander Killed by Police']
df['Total # of White People Killed (2013-2021)'] = df['White People Killed by Police (1/1/2013-12/31/2019)'] + df['White People Killed by Police']
df['Total # of People Killed (2013-2021)'] = df['Total # of Black People Killed (2013-2021)'] + df['Total # of Hispanic People Killed (2013-2021)'] + df['Total # of Native American People Killed (2013-2021)'] + df['Total # of Asian People Killed (2013-2021)'] + df['Total # of Pacific Islanders Killed (2013-2021)'] + df['Total # of White People Killed (2013-2021)']
df['Total # of Arrests (2013-2018)'] = df['2013 Total Arrests (UCR Data)'] + df['2014 Total Arrests'] + df['2015 Total Arrests'] + df['2016 Total Arrests'] + df['2017 Total Arrests'] +  df['2018 Total Arrests']

population = [5039877, 732673, 7276316, 3025891, 39237836, 5812069, 3605597, 1003384, 670050, 21781128, 10799566, 1441553, 1900923, 12671469, 6805985, 3193079, 2934582, 4509394, 4624047, 1372247, 6165129, 6984723, 10050811, 5707390, 2949965, 6168187, 1104271, 1963692, 3143991, 1388992, 9267130, 2115877, 19835913, 10551162, 774948, 11780017, 3986639, 4246155, 12964056, 1095610, 5190704, 895376, 6975218, 29527941, 3343552, 645570, 8642274, 7738692, 1782959, 5895908, 578803]
df['Total Population (2021)'] = population

budget = [449, 524, 253, 413, 526, 370, 349, 752, 931, 440, 268, 358, 252, 188, 397, 418, 321, 184, 193, 179, 813, 583, 278, 208, 171, 159, 570, 559, 455, 354, 407, 367, 320, 202, 233, 192, 475, 359, 295, 237, 157, 473, 327, 302, 291, 570, 302, 307, 237, 259, 779]
df['Budget Per Capita for Police'] = budget

percentages_of_education = [0.190, 0.247, 0.235, 0.167, 0.266, 0.327, 0.314, 0.250, 0.391, 0.223, 0.243, 0.262, 0.217, 0.261, 0.194, 0.212, 0.258, 0.171, 0.187, 0.229, 0.314, 0.332, 0.218, 0.274, 0.169, 0.216, 0.244, 0.237, 0.182, 0.287, 0.298, 0.235, 0.274, 0.225, 0.220, 0.211, 0.203, 0.251, 0.224, 0.256, 0.204, 0.215, 0.196, 0.232, 0.261, 0.294, 0.295, 0.277, 0.148, 0.224, 0.219]
population = [4447207.0, 626933.0, 5130247.0, 2673293.0, 33871653.0, 4302086.0, 3405650.0, 783559.0, 572086.0, 15982571.0, 8186653.0, 1211497.0, 1293857.0, 12419927.0, 6080827.0, 2926538.0, 2688925.0, 4042193.0, 4469035.0, 1274779.0, 5296647.0, 6349364.0, 9938823.0, 4919631.0, 2844754.0, 5596564.0, 902200.0, 1711230.0, 1998250.0, 1235807.0, 8414764.0, 1819017.0, 18977026.0, 8046346.0, 642237.0, 11353336.0, 3450451.0, 3421524.0, 12280548.0, 1048259.0, 4012023.0, 754858.0, 5689427.0, 20851028.0, 2233183.0, 608613.0, 7079057.0, 5894281.0, 1808193.0, 5353757.0, 493786.0]

product = np.dot(percentages_of_education, population)

df['Total # of Educated'] = product

pupil_sales = [9696, 17726, 8239, 10139, 12498, 10202, 20635, 15639, 22406, 9346, 10810, 15242, 7771, 15741, 10262, 11732, 11653, 11110, 11452, 14145, 14762, 17058, 12345, 12975, 8935, 10810, 11680, 12491, 9417, 16893, 20021, 9582, 24040, 9377, 13758, 13027, 8239, 11920, 16395, 16121, 10856, 10073, 9544, 9606, 7628, 9340, 12216, 12995, 11334, 12285, 16224]

df['Budget Per Pupil'] = pupil_sales

df.drop(['Violent crimes 2013 (if reported by agency)'], axis=1, inplace=True)
df.drop(['Violent crimes 2014 (if reported by agency)'], axis=1, inplace=True)
df.drop(['Violent crimes 2015 (if reported by agency)'], axis=1, inplace=True)
df.drop(['Violent crimes 2016 (if reported by agency)'], axis=1, inplace=True)
df.drop(['Violent crimes 2017 (if reported by agency)'], axis=1, inplace=True)
df.drop(['Violent crimes 2018 (if reported by agency)'], axis=1, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
def convert_to_numerical(df, column):
  categorical_features = df[column]
  le.fit(categorical_features)
  numerical_features = le.transform(categorical_features)
  df.insert(df.columns.get_loc(column) + 1, column = (column + '_categorical'), value = numerical_features)

convert_to_numerical(df, 'State')

In [ ]:
X = df[['State_categorical', 'Black-White Dissimilarity Index', 'Total # of Arrests (2013-2018)', 'Total Population (2021)', 'Budget Per Capita for Police', 'Total # of Educated']]
Y = df[['Total # of People Killed (2013-2021)']]

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

yy_test = Y_test.to_numpy()

In [ ]:
from sklearn import tree


clf = tree.DecisionTreeRegressor(min_samples_split = 6, max_depth = 4, max_leaf_nodes=4)

clf = clf.fit(X_train, Y_train)
prediction_test = clf.predict(X_test)

Y_predictions = clf.predict(X_test)

clf.score(X_test, Y_test)

np.sqrt(((yy_test -Y_predictions)** 2).mean())

40.395872126873044

In [ ]:
from sklearn.metrics import mean_squared_error
error = mean_squared_error(Y_test, prediction_test)

(np.sqrt(error)/df['Total # of People Killed (2013-2021)'].mean())

from sklearn.metrics import mean_absolute_error
error2 = mean_absolute_error(Y_test, prediction_test)

((error2)/df['Total # of People Killed (2013-2021)'].mean())

0.46627935701432977

In [ ]:
from sklearn.metrics import r2_score
r2_score1 = r2_score(Y_test, prediction_test)

r2_score1

0.1309651068945138

In [ ]:
from sklearn.neural_network import MLPRegressor
regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, Y_train)

reger1 = regr.score(X_test, Y_test)

Y_predictions = regr.predict(X_test)

np.sqrt(((yy_test -Y_predictions)** 2).mean())

from sklearn.metrics import mean_squared_error
error = mean_squared_error(Y_test, Y_predictions)

(np.sqrt(error)/df['Total # of People Killed (2013-2021)'].mean())

from sklearn.metrics import mean_absolute_error
error2 = mean_absolute_error(Y_test, Y_predictions)

((error2)/df['Total # of People Killed (2013-2021)'].mean())

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

620.7497644231815

In [ ]:
Y_predictions

array([   4643.39845103,     589.03858573,   30016.04758621,
         -7458.87869883,   -4895.64909123,   -2814.30287767,
         -1965.56196776, -110113.83411818,   -4694.38987456,
         38964.11382216,  -79174.09252104,  -41882.06206438,
         14702.76632848,   -3280.1576125 ,   26227.38541386,
       -103227.23226703,   13498.94448484])

In [ ]:
my_list = df.columns.values.tolist()
 
my_list

['State',
 'State_categorical',
 'Black People Killed by Police',
 'Hispanic People Killed by Police',
 'Native American People Killed by Police',
 'Asian People Killed By Police',
 'Pacific Islander Killed by Police',
 'White People Killed by Police',
 'Black-White Dissimilarity Index',
 'Black People Killed by Police (1/1/2013-12/31/2019)',
 'Hispanic People Killed by Police (1/1/2013-12/31/2019)',
 'Native American People Killed by Police (1/1/2013-12/31/2019)',
 'Asian People Killed by Police (1/1/2013-12/31/2019)',
 'Pacific Islanders Killed by Police (1/1/2013-12/31/2019)',
 'White People Killed by Police (1/1/2013-12/31/2019)',
 'Unknown Race People Killed by Police (1/1/2013-12/31/2019)',
 'Black-White Dissimilarity Index (2010)',
 'Murder and\n  nonnegligent manslaughter',
 '2013 Total Arrests (UCR Data)',
 '2014 Total Arrests',
 '2015 Total Arrests',
 '2016 Total Arrests',
 '2017 Total Arrests',
 '2018 Total Arrests',
 'Total # of Black People Killed (2013-2021)',
 'Total # of Hispanic People Killed (2013-2021)',
 'Total # of Native American People Killed (2013-2021)',
 'Total # of Asian People Killed (2013-2021)',
 'Total # of Pacific Islanders Killed (2013-2021)',
 'Total # of White People Killed (2013-2021)',
 'Total # of People Killed (2013-2021)',
 'Total # of Arrests (2013-2018)',
 'Total Population (2021)',
 'Budget Per Capita for Police',
 'Total # of Educated',
 'Budget Per Pupil']

In [ ]:
from sklearn.preprocessing import MinMaxScaler

y = pd.get_dummies(df.State, prefix="State")

data = pd.concat([df, y], sort=False, axis=1)

data["budget_normalized"] = MinMaxScaler().fit_transform(np.array(data["Budget Per Pupil"]).reshape(-1,1))
data["population_normalized"] = MinMaxScaler().fit_transform(np.array(data["Total Population (2021)"]).reshape(-1,1))
#df["arrests_normalized"] = MinMaxScaler().fit_transform(np.array(df["Total #of Arrests(2013-2018"]).reshape(-1,1))

In [ ]:
preds = clf.predict(X_test)

print(np.sqrt(mean_squared_error(y_test, preds)))
print(mean_absolute_error(y_test, preds))
print(r2_score(y_test,preds))

data["Total # of People Killed (2013-2021)"].mean()

34.95305835710229
22.25046835449644
0.05377075621269889

46.2798088013486

In [ ]:
x = pd.get_dummies(df.State, prefix='State')

df_dummies = pd.concat([df, x], sort=False, axis=1)

df_dummies.columns

Index(['State', 'State_categorical', 'Black People Killed by Police',
       'Hispanic People Killed by Police',
       'Native American People Killed by Police',
       'Asian People Killed By Police', 'Pacific Islander Killed by Police',
       'White People Killed by Police', 'Black-White Dissimilarity Index',
       'Black People Killed by Police (1/1/2013-12/31/2019)',
       'Hispanic People Killed by Police (1/1/2013-12/31/2019)',
       'Native American People Killed by Police (1/1/2013-12/31/2019)',
       'Asian People Killed by Police (1/1/2013-12/31/2019)',
       'Pacific Islanders Killed by Police (1/1/2013-12/31/2019)',
       'White People Killed by Police (1/1/2013-12/31/2019)',
       'Unknown Race People Killed by Police (1/1/2013-12/31/2019)',
       'Black-White Dissimilarity Index (2010)',
       'Murder and\n  nonnegligent manslaughter',
       '2013 Total Arrests (UCR Data)', '2014 Total Arrests',
       '2015 Total Arrests', '2016 Total Arrests', '2017 Total Arrests',
       '2018 Total Arrests', 'Total # of Black People Killed (2013-2021)',
       'Total # of Hispanic People Killed (2013-2021)',
       'Total # of Native American People Killed (2013-2021)',
       'Total # of Asian People Killed (2013-2021)',
       'Total # of Pacific Islanders Killed (2013-2021)',
       'Total # of White People Killed (2013-2021)',
       'Total # of People Killed (2013-2021)',
       'Total # of Arrests (2013-2018)', 'Total Population (2021)',
       'Budget Per Capita for Police', 'Total # of Educated',
       'Budget Per Pupil', 'State_Alabama', 'State_Alaska', 'State_Arizona',
       'State_Arkansas', 'State_California', 'State_Colorado',
       'State_Connecticut', 'State_Delaware', 'State_District of Columbia',
       'State_Florida', 'State_Georgia', 'State_Hawaii', 'State_Idaho',
       'State_Illinois', 'State_Indiana', 'State_Iowa', 'State_Kansas',
       'State_Kentucky', 'State_Louisiana', 'State_Maine', 'State_Maryland',
       'State_Massachusetts', 'State_Michigan', 'State_Minnesota',
       'State_Mississippi', 'State_Missouri', 'State_Montana',
       'State_Nebraska', 'State_Nevada', 'State_New Hampshire',
       'State_New Jersey', 'State_New Mexico', 'State_New York',
       'State_North Carolina', 'State_North Dakota', 'State_Ohio',
       'State_Oklahoma', 'State_Oregon', 'State_Pennsylvania',
       'State_Rhode Island', 'State_South Carolina', 'State_South Dakota',
       'State_Tennessee', 'State_Texas', 'State_Utah', 'State_Vermont',
       'State_Virginia', 'State_Washington', 'State_West Virginia',
       'State_Wisconsin', 'State_Wyoming'],
      dtype='object')

In [ ]:
X

,Black-White Dissimilarity Index (2010),Murder and\n nonnegligent manslaughter,Total # of Arrests (2013-2018),Total Population (2021),Budget Per Capita for Police,Total # of Educated,State_Alabama,State_Alaska,State_Arizona,State_Arkansas,...,State_Texas,State_Utah,State_Vermont,State_Virginia,State_Washington,State_West Virginia,State_Wisconsin,State_Wyoming,budget_normalized,population_normalized
0,62.560000,52.000000,140573.000000,5039877,449,6.863449e+07,1,0,0,0,...,0,0,0,0,0,0,0,0,0.126005,0.115395
1,34.330000,12.000000,87874.000000,732673,524,6.863449e+07,0,1,0,0,...,0,0,0,0,0,0,0,0,0.615282,0.003980
2,30.820000,41.000000,128298.166667,7276316,253,6.863449e+07,0,0,1,0,...,0,0,0,0,0,0,0,0,0.037229,0.173246
3,52.346446,71.017019,153136.060066,3025891,413,6.863449e+07,0,0,0,1,...,0,0,0,0,0,0,0,0,0.152998,0.063299
4,38.651176,43.823529,97406.529412,39237836,526,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.296734,1.000000
5,39.373333,109.666667,132997.000000,5812069,370,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.156836,0.135370
6,52.346446,71.017019,153136.060066,3605597,349,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.792530,0.078295
7,52.346446,71.017019,153136.060066,1003384,752,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.488118,0.010983
8,72.180000,31.000000,263385.000000,670050,931,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.900439,0.002360
9,58.325000,65.333333,109795.000000,21781128,440,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.104680,0.548444
10,74.120000,93.000000,145847.000000,10799566,268,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.193883,0.264382
11,30.280000,242.000000,140573.000000,1441553,358,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.463929,0.022317
12,52.346446,71.017019,153136.060066,1900923,252,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.008713,0.034200
13,82.480000,411.000000,495190.000000,12671469,188,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.494333,0.312803
14,55.080000,24.000000,140213.000000,6805985,397,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.160492,0.161080
15,52.346446,71.017019,153136.060066,3193079,418,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.250061,0.067624
16,49.270000,15.000000,50569.000000,2934582,321,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.245247,0.060937
17,48.185000,9.500000,156187.000000,4509394,184,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.212162,0.101673
18,67.285000,193.000000,122987.500000,4624047,193,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.233000,0.104639
19,52.346446,71.017019,153136.060066,1372247,179,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.397087,0.020524
20,68.900000,211.000000,211003.000000,6165129,813,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.434682,0.144502
21,69.170000,53.000000,66870.000000,6984723,583,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.574580,0.165703
22,59.170000,21.000000,70287.000000,10050811,278,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.287412,0.245014
23,47.180000,84.500000,73555.000000,5707390,208,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.325798,0.132662
24,52.346446,71.017019,153136.060066,2949965,171,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.079637,0.061335
25,63.755000,12.500000,92959.000000,6168187,159,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.193883,0.144582
26,52.346446,71.017019,153136.060066,1104271,570,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.246893,0.013592
27,45.095000,19.000000,105371.000000,1963692,559,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.296308,0.035823
28,28.092500,29.500000,155159.250000,3143991,455,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.109006,0.066354
29,52.346446,71.017019,153136.060066,1388992,354,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.564526,0.020957
30,64.940000,54.500000,55442.500000,9267130,407,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.755118,0.224742
31,28.480000,30.000000,138998.000000,2115877,367,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.119059,0.039760
32,66.296667,60.333333,727056.333333,19835913,320,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,1.000000,0.498127
33,51.728000,19.800000,98590.000000,10551162,202,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.106568,0.257957
34,52.346446,71.017019,153136.060066,774948,233,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.373507,0.005074
35,57.422500,63.250000,81602.750000,11780017,192,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.328967,0.289744
36,48.260000,24.500000,98634.000000,3986639,475,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.037229,0.088151
37,38.640000,12.000000,131508.000000,4246155,359,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.261516,0.094864
38,64.950000,59.000000,237244.000000,12964056,295,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.534182,0.320372
39,52.346446,71.017019,153136.060066,1095610,237,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.517487,0.013368
40,52.346446,71.017019,153136.060066,5190704,157,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.196685,0.119297
41,52.346446,71.017019,153136.060066,895376,473,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.148976,0.008189
42,58.510000,51.500000,239580.500000,6975218,327,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,0,0.116744,0.165457
43,43.230000,49.538462,132999.846154,29527941,302,6.863449e+07,0,0,0,0,...,1,0,0,0,0,0,0,0,0.120522,0.748832
44,52.346446,71.017019,153136.060066,3343552,291,6.863449e+07,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000000,0.071516
45,52.346446,71.017019,153136.060066,645570,570,6.863449e+07,0,0,0,0,...,0,0,1,0,0,0,0,0,0.104314,0.001727
46,42.940000,42.333333,80959.666667,8642274,302,6.863449e+07,0,0,0,0,...,0,0,0,1,0,0,0,0,0.279552,0.208579
47,36.705000,84.500000,86389.500000,7738692,307,6.863449e+07,0,0,0,0,...,0,0,0,0,1,0,0,0,0.327017,0.185206
48,52.346446,71.017019,153136.060066,1782959,237,6.863449e+07,0,0,0,0,...,0,0,0,0,0,1,0,0,0.225810,0.031148
49,53.375000,90.500000,110521.500000,5895908,259,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,1,0,0.283756,0.137538
50,52.346446,71.017019,153136.060066,578803,779,6.863449e+07,0,0,0,0,...,0,0,0,0,0,0,0,1,0.523763,0.000000

In [ ]:
print(Y_test, preds)

NameError: ignored